### ISSUE TITLE
Unityのイベント関数がよく分からない について

### ISSUE THREAD

**Issue by walkerjito** [gen0083/blog_android.gcreate.jp#87]
自分もふと、そう言えば Unity のイベント関数には override 使ってないな、と思って調べ、記事を読ませていただきました。
そこから発展して「Unity イベント関数 override しない」で検索し以下のようなサイトを発見しました（teratail）
https://teratail.com/questions/36597
それによると、Unity は IL2CPP のスクリプティングランタイムで Monobehaviour の特定のメソッドを持っていたら所定のリストに組み込まみ、ゲーム中はこのリストからメソッドを呼んでいるそうです。 

詳しくは Unity の公式ブログ[Update()を10000回呼ぶ]を回答者さんが提示しております。
もしも既に問題が解決していましたら余計な事かも知れませんが、一応お伝えしておこうと思いましてコメントした次第です。
それでは。

**Comment by gen0083** [comment]
ありがとうございます！
わざわざコメントいただいたのに気づかずすみません・・・:bow:
